version: "2.2"
services:
  discovery:
    build: ../../discovery-server
    ports:
      - "8761:8761"
    image: discovery-server

  freelancer-ms:
    build: ../../Freelancer-MS
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "8800:8800"
    image: freelancer-service


  offre_emploi-ms:
    build: ../../offre_emploi-MS
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "8880:8880"
    image: offre_emploi-service

  conges-service:
    build: ../../Conges-MS
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/projet?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "8806:8806"
    image: conges-service
    

  contact-ms:
    build: ../../Contact-MS
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/projet?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "8805:8805"
    image: contact-service
    

  mysql:
    image: mysql:8.0.23
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=projet
      - MYSQL_PASSWORD=
    ports:
      - "3307:3306"
    volumes:
      - /var/lib/mysql

  projet-ms:
      build: ../../Projet_MS
      environment:
         - spring.datasource.url=jdbc:mysql://mysql:3306/projet?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
         - SPRING_DATASOURCE_USERNAME=root
         - SPRING_DATASOURCE_PASSWORD=root
         - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      ports:
         - "8801:8801"
      image: projet-service

  formation-ms:
     build: ../../Formation-Node-MS
     environment:
         - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
         - MONGO_HOST=mongos  # Utilisez le nom du service MongoDB (mongos) comme hôte
         - MONGO_PORT=27017   # Le port par défaut de MongoDB
     ports:
         - "4401:4401"
     image: formation-service


  config:
    build: ../../config-server
    command: "--spring.profiles.active=native --spring.cloud.config.server.native.searchLocations=/config"
    volumes:
      - ./src/main/resources/centralRepo:/config
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - spring.profiles.active=native
    ports:
      - "8066:8066"
    image: config-server

  gateway:
    build: ../../zuul-server
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "8762:8762"
    image: gateway-server

  mongos:
    image: mongo:latest
    ports:
      - "27017:27017"

    #http://localhost:8762/projet-service
    #http://localhost:8762/freelancer-service
    #http://localhost:8762/offre_emploi-service
    #http://localhost:8762/conges-service
    #http://localhost:8762/contact-service
    #http://localhost:8888/config-server/default